controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

2fa_login_check:
    path: /2fa_check
    controller: Scheb\TwoFactorBundle\Controller\FormController::check
