parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/images'
    photo_dir_products: '%kernel.project_dir%/public/uploads/products'
    pusher_key: '%env(PUSHER_KEY)%'
    pusher_secret: '%env(PUSHER_SECRET)%'
    pusher_app_id: '%env(PUSHER_APP_ID)%'
    pusher_cluster: '%env(PUSHER_CLUSTER)%'
    projectDir: '%kernel.project_dir%/public/uploads/certifs'
    videosdk_api_key: '%env(VIDEOSDK_API_KEY)%'
    VIDEOSDK_SECRET_KEY: '%env(VIDEOSDK_SECRET_KEY)%'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    linkedin_client_id: '%env(LINKEDIN_CLIENT_ID)%'
    linkedin_client_secret: '%env(LINKEDIN_CLIENT_SECRET)%'

services:
    App\Service\CertificateGeneratorService:
        arguments:
            $projectDir: '%kernel.project_dir%/public/uploads/certifs'

    App\Service\ParticipationCalculatorService:
        arguments:
            $attendanceRepository: '@App\Repository\AttendanceRepository'
            $sessionRepository: '@App\Repository\SessionRepository'
            $participantEventRepository: '@App\Repository\ParticipantEventRepository'

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\SecurityController: ~

    App\EventListener\LoginListener:
        class: App\EventListener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
